In [3]:
# !pip install numpy


^C


  Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB 131.3 kB/s eta 0:01:58
   ---------------------------------------- 0.1/15.5 MB 255.1 kB/s eta 0:01:01
   ---------------------------------------- 0.1/15.5 MB 255.1 kB/s eta 0:01:01
   ---------------------------------------- 0.1/15.5 MB 255.1 kB/s eta 0:01:01
   ---------------------------------------- 0.1/15.5 MB 201.8 kB/s eta 0:01:17
   ---------------------------------------- 0.1/15.5 MB 201.8 kB/s eta 0:01:17
   --------------------------------

In [5]:
import numpy as np

In [8]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [20]:
# 1d aryy 

arr = np.array([1, 2, 3, 4, 5])

print(arr)
# 2d arry
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
# to check the dimension 
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
0
1
2
3


In [11]:
a = np.array([1,2,3,4,45,5,6,7,7,8], dtype= 'int16')
a. dtype


dtype('int16')

In [21]:
arr = np.array([1, 2, 3, 4, '5'])
print(a.itemsize)
print(a.size)
print(type(arr))
print(arr.dtype)
print(arr.nbytes)


4
1
<class 'numpy.ndarray'>
<U11
220


In [23]:
#to assess the indexingg 

arr = np.array([1, 2, 3, 4])

print(arr[3])

4


In [31]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])


2nd element on 1st row:  2
 elements of rows  []


In [32]:
#slicing in arry 
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [26]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [33]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

#Return every other element from the entire array:

[1 3 5 7]


In [34]:
# From the second element, slice elements from index 1 to index 4 (not included):
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [41]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
# arr[0][1:]=[100,101]
arr[1][:] = [100]
arr

array([[  1,   2,   3,   4,   5],
       [100, 100, 100, 100, 100]])

In [45]:
a=np.zeros((3,3))
print(a)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [54]:
#change the data type 
print(
    a.dtype)
a = a.astype('int16')
print(a.dtype)


int16
int16


In [57]:
a = np.ones((2,3))
a
print(
    a.dtype)
a = a.astype('int16')
print(a.dtype)

float64
int16


In [59]:
b = np.ones(a.shape)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [64]:


arr = np.array([ [ [  [1, 2, 3],
                     [4, 5, 6],
                       [7, 8, 9] ] ] ])
print(arr)
b = np.ones((3,3,3))
print(b)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [66]:
a= np.full((3,3,),911)
print(a)

[[911 911 911]
 [911 911 911]
 [911 911 911]]


In [71]:
a= np.zeros((4,3,2))
print(a)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [72]:
np.random.rand(4,3,1)

array([[[0.26015404],
        [0.77146088],
        [0.03199316]],

       [[0.78170818],
        [0.28536201],
        [0.93466175]],

       [[0.55382627],
        [0.35920363],
        [0.61808956]],

       [[0.25785595],
        [0.58926945],
        [0.25073467]]])

In [89]:
np.random.random_sample(a.shape)


array([[[0.63421263, 0.77535077],
        [0.87560704, 0.70105251],
        [0.05138644, 0.10419688]],

       [[0.59934938, 0.69209867],
        [0.31818726, 0.28201177],
        [0.34104126, 0.71183604]],

       [[0.52522785, 0.93506113],
        [0.2721688 , 0.26699725],
        [0.35499428, 0.15326147]],

       [[0.01514275, 0.09827301],
        [0.9086064 , 0.28530151],
        [0.57172076, 0.41677455]]])

In [92]:
np.random.randint(100, size=(2,3))
#to change the data type 

array([[42, 17, 81],
       [33, 50, 10]])

In [94]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [96]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [98]:
b=np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [102]:
c=a+b
print(c)
np.cos(30)

[ 2  4  6  8 10]


0.15425144988758405

In [106]:
a= np.ones((2,3))
print(a)
b=np.full((3,2),2)


[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
np.linalg.det